import asyncio
import json
import os
import stat
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import decky


CONFIG_DIR = Path(decky.DECKY_USER_HOME) / ".config" / "prelaunch-scripts"
SETTINGS_PATH = CONFIG_DIR / "settings.json"
RUNNER_PATH = CONFIG_DIR / "run"
LOG_PATH = CONFIG_DIR / "last-run.log"
MAX_TIMEOUT_SECONDS = 3600

DEFAULT_SETTINGS = {
    "enabled": True,
    "script_path": "",
    "timeout_seconds": 60,
}


def normalize_settings(settings):
    raw_settings = settings if isinstance(settings, dict) else {}

    timeout_value = raw_settings.get("timeout_seconds", DEFAULT_SETTINGS["timeout_seconds"])
    try:
        timeout_seconds = int(timeout_value)
    except (TypeError, ValueError):
        timeout_seconds = DEFAULT_SETTINGS["timeout_seconds"]

    return {
        "enabled": bool(raw_settings.get("enabled", DEFAULT_SETTINGS["enabled"])),
        "script_path": str(raw_settings.get("script_path", "")).strip(),
        "timeout_seconds": max(1, min(timeout_seconds, MAX_TIMEOUT_SECONDS)),
    }


def read_settings():
    if not SETTINGS_PATH.exists():
        return DEFAULT_SETTINGS.copy()

    try:
        with open(SETTINGS_PATH, "r", encoding="utf-8") as file:
            data = json.load(file)
            return normalize_settings(data)
    except Exception:
        return DEFAULT_SETTINGS.copy()


def write_settings(settings):
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    normalized = normalize_settings(settings)

    with open(SETTINGS_PATH, "w", encoding="utf-8") as file:
        json.dump(normalized, file, indent=4)

    return normalized


def build_script_command(script: Path):
    if script.suffix == ".sh":
        return ["/usr/bin/bash", str(script)]

    if script.suffix == ".py":
        return [sys.executable, str(script)]

    return [str(script)]


def format_stream(value):
    return (value or "").rstrip()


def script_environment():
    environment = os.environ.copy()

    # Steam/Decky may inject library paths that make normal user tools such as
    # bash load incompatible runtime libraries. Scripts should use the system
    # runtime, while the game command keeps Steam's original environment.
    environment.pop("LD_LIBRARY_PATH", None)
    environment.pop("LD_PRELOAD", None)

    return environment


def run_script(script: Path, timeout_seconds: int):
    command = build_script_command(script)

    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            env=script_environment(),
        )
        stdout = format_stream(result.stdout)
        stderr = format_stream(result.stderr)
        message = f"Exit code: {result.returncode}"
        ok = result.returncode == 0
    except subprocess.TimeoutExpired as error:
        stdout = format_stream(error.stdout)
        stderr = format_stream(error.stderr)
        message = f"Timed out after {timeout_seconds} seconds."
        ok = False
        result = None
    except Exception as error:
        stdout = ""
        stderr = ""
        message = str(error)
        ok = False
        result = None

    log_lines = [
        "=== PRELAUNCH SCRIPT ===",
        f"Time: {datetime.now().isoformat(timespec='seconds')}",
        f"Script: {script}",
        f"Command: {command}",
        f"Timeout seconds: {timeout_seconds}",
        f"Status: {message}",
        "",
        "STDOUT:",
        stdout or "(empty)",
        "",
        "STDERR:",
        stderr or "(empty)",
    ]

    if result is not None:
        log_lines.insert(4, f"Return code: {result.returncode}")

    return {
        "ok": ok,
        "message": message,
        "log": "\n".join(log_lines) + "\n",
    }


class Plugin:
    async def _main(self):
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        await self.install_runner()
        decky.logger.info("DeckyScripts loaded")

    async def get_settings(self):
        return read_settings()

    async def save_settings(self, settings):
        write_settings(settings)
        return True

    async def get_launch_command(self):
        return f"{RUNNER_PATH} %command%"

    async def install_runner(self):
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)

        runner_code = f'''#!/usr/bin/env -S -u LD_LIBRARY_PATH -u LD_PRELOAD /usr/bin/python3
"""DeckyScripts launcher generated by the plugin."""
import runpy

runpy.run_path({str(Path(decky.DECKY_PLUGIN_DIR) / "run.py")!r}, run_name="__main__")
'''

        RUNNER_PATH.write_text(runner_code, encoding="utf-8")

        current = os.stat(RUNNER_PATH)
        os.chmod(
            RUNNER_PATH,
            current.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH,
        )

        return str(RUNNER_PATH)

    async def get_log(self):
        if not LOG_PATH.exists():
            return ""

        return LOG_PATH.read_text(encoding="utf-8", errors="replace")

    async def test_script(self):
        settings = read_settings()
        script_path = settings.get("script_path", "").strip()
        timeout_seconds = settings.get("timeout_seconds", DEFAULT_SETTINGS["timeout_seconds"])

        if not script_path:
            return {
                "ok": False,
                "message": "No script path set.",
            }

        script = Path(script_path).expanduser()

        if not script.exists():
            return {
                "ok": False,
                "message": f"Script not found: {script}",
            }

        result = await asyncio.to_thread(run_script, script, timeout_seconds)
        LOG_PATH.write_text(
            "=== TEST RUN ===\n"
            f"Time: {datetime.now().isoformat(timespec='seconds')}\n"
            f"{result['log']}",
            encoding="utf-8",
        )

        return {
            "ok": result["ok"],
            "message": result["message"],
        }

    async def _unload(self):
        decky.logger.info("DeckyScripts unloaded")
